hospital_dict = [
 {'facId': '100242',
  'filenames': ['620976863_gulf-coast-regional-medical-center_standardcharges.csv'],
  'hospital': 'gulf coast regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '131310',
  'filenames': ['3ccc0adfd87a44bf8d6205cb4c56de6c.csv'],
  'hospital': 'st lukes jerome',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '131312',
  'filenames': ['b8553be975ca49f4b7982143d18238a7.csv'],
  'hospital': 'st lukes mccall',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '20017',
  'filenames': ['611000033_alaska-regional-hospital_standardcharges.csv'],
  'hospital': 'alaska regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '260214',
  'filenames': ['20-0851062_belton-regional-medical-center_standardcharges.csv'],
  'hospital': 'belton regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100213',
  'filenames': ['62-1113740_blake-medical-center_standardcharges.csv'],
  'hospital': 'blake medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100243',
  'filenames': ['610947837_brandon-regional-hospital_standardcharges.csv'],
  'hospital': 'brandon regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100254',
  'filenames': ['621091430_capital-regional-medical-center_standardcharges.csv'],
  'hospital': 'capital regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110030',
  'filenames': ['58-2433438_cartersville-medical-center_standardcharges.csv'],
  'hospital': 'cartersville medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '260095',
  'filenames': ['45-0503121_centerpoint-medical-center_standardcharges.csv'],
  'hospital': 'centerpoint medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100161',
  'filenames': ['591978725_central-florida-regional-hospital_standardcharges.csv'],
  'hospital': 'central florida regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100023',
  'filenames': ['471455535_citrus-memorial-hospital_standardcharges.csv'],
  'hospital': 'citrus memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '420030',
  'filenames': ['570712623_colleton-medical-center_standardcharges.csv'],
  'hospital': 'colleton medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100166',
  'filenames': ['611258724_doctors-hospital-of-sarasota_standardcharges.csv'],
  'hospital': 'doctors hospital of sarasota',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '494023',
  'filenames': ['621410313_dominion-hospital_standardcharges.csv'],
  'hospital': 'dominion hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '130018',
  'filenames': ['82-0436622_eastern-idaho-rmc_standardcharges.csv'],
  'hospital': 'eastern idaho regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110192',
  'filenames': ['58-2433432_eastside-medical-center_standardcharges.csv'],
  'hospital': 'eastside medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100267',
  'filenames': ['351611050_englewood-community-hospital_standardcharges.csv'],
  'hospital': 'englewood community hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110125',
  'filenames': ['621817469_fairview-park-hospital_standardcharges.csv'],
  'hospital': 'fairview park hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100236',
  'filenames': ['650252846_fawcett-memorial-hospital_standardcharges.csv'],
  'hospital': 'fawcett memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100223',
  'filenames': ['611259833_fort-walton-beach-medical-center_standardcharges.csv'],
  'hospital': 'fort walton beach medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '180127',
  'filenames': ['61-0859329_frankfort-regional-medical-ctr_standardcharges.csv'],
  'hospital': 'frankfort regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '300014',
  'filenames': ['842462186_frisbie-memorial-hospital_standardcharges.csv'],
  'hospital': 'frisbie memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '250123',
  'filenames': ['Gross-revenue-by-case-by-DRG-FY18.xlsx'],
  'hospital': 'garden park medical center',
  'url': 'https://singingriverhealthsystem.com/wp-content/uploads/2019/10/'},
 {'facId': '50257',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50380',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50471',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '150042',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '360134',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '390066',
  'filenames': ['62-1763090_good-samaritan-hospital_standardcharges.csv'],
  'hospital': 'good samaritan hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450617',
  'filenames': ['621801360_hca-houston-clear-lake_standardcharges.csv'],
  'hospital': 'hca houston healthcare clear lake',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450222',
  'filenames': ['621801361_hca-houston-conroe_standardcharges.csv'],
  'hospital': 'hca houston healthcare conroe',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450638',
  'filenames': ['261512163_hca-houston-northwest_standardcharges.csv'],
  'hospital': 'hca houston healthcare northwest',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '670106',
  'filenames': ['GulfCoastDivision_HCAHoustonPearland_CM.csv'],
  'hospital': 'hca houston healthcare pearland',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450097',
  'filenames': ['621801359_hca-houston-southeast_standardcharges.csv'],
  'hospital': 'hca houston healthcare southeast',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450670',
  'filenames': ['821349955_hca-houston-tomball_standardcharges.csv'],
  'hospital': 'hca houston healthcare tomball',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450644',
  'filenames': ['621801363_hca-houston-west_standardcharges.csv'],
  'hospital': 'hca houston healthcare west',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '490118',
  'filenames': ['62-1113733_henrico-doctors-hospital_standardcharges.csv'],
  'hospital': 'henrico doctors hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60065',
  'filenames': ['84-1321373_north-suburban_standardcharges.csv'],
  'hospital': 'north suburban medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60065',
  'filenames': ['84-1321373_north-suburban_standardcharges.csv'],
  'hospital': 'north suburban medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60065',
  'filenames': ['84-1321373_north-suburban_standardcharges.csv'],
  'hospital': 'north suburban medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60065',
  'filenames': ['84-1321373_north-suburban_standardcharges.csv'],
  'hospital': 'north suburban medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60014',
  'filenames': ['84-1321373_p-sl-medical-center_standardcharges.csv'],
  'hospital': 'presbyterianst lukes medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60032',
  'filenames': ['84-1321373_rose-medical-center_standardcharges.csv'],
  'hospital': 'rose medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60032',
  'filenames': ['84-1321373_rose-medical-center_standardcharges.csv'],
  'hospital': 'rose medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60032',
  'filenames': ['84-1321373_rose-medical-center_standardcharges.csv'],
  'hospital': 'rose medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60032',
  'filenames': ['84-1321373_rose-medical-center_standardcharges.csv'],
  'hospital': 'rose medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60112',
  'filenames': ['84-1321373_sky-ridge-medical-center_standardcharges.csv'],
  'hospital': 'sky ridge medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60112',
  'filenames': ['84-1321373_sky-ridge-medical-center_standardcharges.csv'],
  'hospital': 'sky ridge medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60112',
  'filenames': ['84-1321373_sky-ridge-medical-center_standardcharges.csv'],
  'hospital': 'sky ridge medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60112',
  'filenames': ['84-1321373_sky-ridge-medical-center_standardcharges.csv'],
  'hospital': 'sky ridge medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '500027',
  'filenames': ['84-1321373_swedish-medical-center_standardcharges.csv'],
  'hospital': 'swedish medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '500027',
  'filenames': ['84-1321373_swedish-medical-center_standardcharges.csv'],
  'hospital': 'swedish medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '500027',
  'filenames': ['84-1321373_swedish-medical-center_standardcharges.csv'],
  'hospital': 'swedish medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '500027',
  'filenames': ['84-1321373_swedish-medical-center_standardcharges.csv'],
  'hospital': 'swedish medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100049',
  'filenames': ['822084329_highlands-regional-medical-center_standardcharges.csv'],
  'hospital': 'highlands regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100080',
  'filenames': ['62-1694180_jfk-medical-center_standardcharges.csv'],
  'hospital': 'jfk medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '310108',
  'filenames': ['62-1694180_jfk-medical-center_standardcharges.csv'],
  'hospital': 'jfk medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '490020',
  'filenames': ['611272888_john-randolph-medical-center_standardcharges.csv'],
  'hospital': 'john randolph medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100209',
  'filenames': ['65-0260078_kendall-regional-medical-center_standardcharges.csv'],
  'hospital': 'kendall regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '261320',
  'filenames': ['48-1301817_lafayette-regional-health-center_standardcharges.csv'],
  'hospital': 'lafayette regional health center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100156',
  'filenames': ['95-4176924_lake-city-medical-center_standardcharges.csv'],
  'hospital': 'lake city medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100248',
  'filenames': ['62-1026428_largo-medical-center_standardcharges.csv'],
  'hospital': 'largo medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '260190',
  'filenames': ['45-0503141_lees-summit-medical-center_standardcharges.csv'],
  'hospital': 'lees summit medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100191',
  'filenames': ['59-2047041_medical-center-of-trinity_standardcharges.csv'],
  'hospital': 'medical center of trinity',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '670103',
  'filenames': ['46-4027347_medical-city-alliance_standardcharges.csv'],
  'hospital': 'medical city alliance',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450675',
  'filenames': ['62-1682201_medical-city-arlington_standardcharges.csv'],
  'hospital': 'medical city arlington',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450634',
  'filenames': ['62-1682213_medical-city-denton_standardcharges.csv'],
  'hospital': 'medical city denton',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450672',
  'filenames': ['62-1682202_medical-city-fort-worth_standardcharges.csv'],
  'hospital': 'medical city fort worth',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450822',
  'filenames': ['62-1650582_medical-city-las-colinas_standardcharges.csv'],
  'hospital': 'medical city las colinas',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450669',
  'filenames': ['62-1682210_medical-city-lewisville_standardcharges.csv'],
  'hospital': 'medical city lewisville',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450087',
  'filenames': ['62-1682205_medical-city-north-hills_standardcharges.csv'],
  'hospital': 'medical city north hills',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450651',
  'filenames': ['62-1682203_medical-city-plano_standardcharges.csv'],
  'hospital': 'medical city plano',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450203',
  'filenames': ['822073410_medical-city-weatherford_standardcharges.csv'],
  'hospital': 'medical city weatherford',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '140185',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '141305',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '141338',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '150072',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '171381',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '281320',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '360092',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '360156',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '370178',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450235',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '451358',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '451386',
  'filenames': ['59-3283127_memorial-hospital-jacksonville_standardcharges.csv'],
  'hospital': 'memorial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100206',
  'filenames': ['364764806_memorial-hospital-of-tampa_standardcharges.csv'],
  'hospital': 'memorial hospital of tampa',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '170182',
  'filenames': ['48-1301826_menorah-medical-center_standardcharges.csv'],
  'hospital': 'menorah medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '290039',
  'filenames': ['621600397_mountainview-hospital_standardcharges.csv'],
  'hospital': 'mountainview hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100204',
  'filenames': ['61-1269294_north-florida-regional-medical-center_standardcharges.csv'],
  'hospital': 'north florida regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100238',
  'filenames': ['610947837_northside-hospital_standardcharges.csv'],
  'hospital': 'northside hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110161',
  'filenames': ['610947837_northside-hospital_standardcharges.csv'],
  'hospital': 'northside hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '10086',
  'filenames': ['611259843_northwest-medical-center_standardcharges.csv'],
  'hospital': 'northwest medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '30085',
  'filenames': ['611259843_northwest-medical-center_standardcharges.csv'],
  'hospital': 'northwest medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100189',
  'filenames': ['611259843_northwest-medical-center_standardcharges.csv'],
  'hospital': 'northwest medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100264',
  'filenames': ['62-1113740_oak-hill-hospital_standardcharges.csv'],
  'hospital': 'oak hill hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100226',
  'filenames': ['61-1269295_orange-park-medical-center_standardcharges.csv'],
  'hospital': 'orange park medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100110',
  'filenames': ['61-1257509_osceola-regional-medical-center_standardcharges.csv'],
  'hospital': 'osceola regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100126',
  'filenames': ['80-0935610_palms-of-pasadena-hospital_standardcharges.csv'],
  'hospital': 'palms of pasadena hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100269',
  'filenames': ['621694178_palms-west-hospital_standardcharges.csv'],
  'hospital': 'palms west hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '300017',
  'filenames': ['020364103_parkland-medical-center_standardcharges.csv'],
  'hospital': 'parkland medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100167',
  'filenames': ['62-1372389_plantation-general-hospital_standardcharges.csv'],
  'hospital': 'plantation general hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100320',
  'filenames': ['90-0811360_poinciana-medical-center_standardcharges.csv'],
  'hospital': 'poinciana medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '300029',
  'filenames': ['02-0364103_portsmouth-regional-hospital_standardcharges.csv'],
  'hospital': 'portsmouth regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '60014',
  'filenames': ['84-1321373_p-sl-medical-center_standardcharges.csv'],
  'hospital': 'presbyterianst luke’s medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100232',
  'filenames': ['47-2762362_putnam-community-medical-center_standardcharges.csv'],
  'hospital': 'putnam community medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '190026',
  'filenames': ['611267229_rapides-regional-medical-center_standardcharges.csv'],
  'hospital': 'rapides regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100252',
  'filenames': ['59-1833934_raulerson-hospital_standardcharges.csv'],
  'hospital': 'raulerson hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110168',
  'filenames': ['58-1123037_redmond-regional-medical-center_standardcharges.csv'],
  'hospital': 'redmond regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100256',
  'filenames': ['62-1113740_regional-medical-center-bayonet-point_standardcharges.csv'],
  'hospital': 'regional medical center bayonet point',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50125',
  'filenames': ['77-0498674_regional-medical-center-of-san-jose_standardcharges.csv'],
  'hospital': 'regional medical center of san jose',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '260027',
  'filenames': ['54-2092552_research-medical-center_standardcharges.csv'],
  'hospital': 'research medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '490107',
  'filenames': ['62-1777534_reston-hospital-center_standardcharges.csv'],
  'hospital': 'reston hospital center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450711',
  'filenames': ['62-1656022_rio-grande-regional-hospital_standardcharges.csv'],
  'hospital': 'rio grande regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50022',
  'filenames': ['33-0751869_riverside-community-hospital_standardcharges.csv'],
  'hospital': 'riverside community hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100259',
  'filenames': ['59-2822337_south-bay-hospital_standardcharges.csv'],
  'hospital': 'south bay hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '290047',
  'filenames': ['743048428_southern-hills-hosp-med-ctr-las-vegas_standardcharges.csv'],
  'hospital': 'southern hills hospital  medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '490141',
  'filenames': ['06-1760818_spotsylvania-regional-medical-center_standardcharges.csv'],
  'hospital': 'spotsylvania regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100260',
  'filenames': ['62-1113740_st-lucie-medical-center_standardcharges.csv'],
  'hospital': 'st lucie medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100180',
  'filenames': ['591174716_st-petersburg-general-hospital_standardcharges.csv'],
  'hospital': 'st petersburg general hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '290003',
  'filenames': ['62-1762537_sunrise-hospital-and-medical-center_standardcharges.csv'],
  'hospital': 'sunrise hospital  medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '150046',
  'filenames': ['351461805_terre-haute-regional-hospital_standardcharges.csv'],
  'hospital': 'terre haute regional hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450804',
  'filenames': ['76-0418502_texas-orthopedic-hospital_standardcharges.csv'],
  'hospital': 'texas orthopedic hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440161',
  'filenames': ['62-1113737_centennial-medical-center_standardcharges.csv'],
  'hospital': 'tristar centennial medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '441311',
  'filenames': ['62-1113737_centennial-medical-center-at-ashland-cit_standardcharges.csv'],
  'hospital': 'tristar ashland city medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440194',
  'filenames': ['62-1321255_hendersonville-medical-center_standardcharges.csv'],
  'hospital': 'tristar hendersonville medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440046',
  'filenames': ['62-1620866_horizon-medical-center_standardcharges.csv'],
  'hospital': 'tristar horizon medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440006',
  'filenames': ['621560757_skyline-medical-center_standardcharges.csv'],
  'hospital': 'tristar skyline medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '190176',
  'filenames': ['621596506_tulane-university-hospital-clinic_standardcharges.csv'],
  'hospital': 'tulane medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100054',
  'filenames': ['59-1836808_twin-cities-hospital_standardcharges.csv'],
  'hospital': 'twin cities hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100224',
  'filenames': ['65-0566885_university-hospital_standardcharges.csv'],
  'hospital': 'university hospital  medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450662',
  'filenames': ['62-1669572_valley-regional-medical-center_standardcharges.csv'],
  'hospital': 'valley regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100231',
  'filenames': ['59-1525468_west-florida-hospital_standardcharges.csv'],
  'hospital': 'west florida hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '130014',
  'filenames': ['36-3525049_west-valley-medical-center_standardcharges.csv'],
  'hospital': 'west valley medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100228',
  'filenames': ['75-2482249_westside-regional-medical-center_standardcharges.csv'],
  'hospital': 'westside regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100124',
  'filenames': ['941340523_SantaRosaMedicalCenter_standardcharges.xlsx',
                '941340523_SantaRosaMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'santa rosa medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '140186',
  'filenames': ['941340523_RiversideMedicalCenter_standardcharges.xlsx',
                '941340523_RiversideMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'riverside medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '191313',
  'filenames': ['941340523_RiversideMedicalCenter_standardcharges.xlsx',
                '941340523_RiversideMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'riverside medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '110192',
  'filenames': ['941105628_WestsideMedicalCenter_standardcharges.xlsx',
                '941105628_WestsideMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'westside medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '100040',
  'filenames': ['590624449_ascension-st-vincents-riverside_standardcharges.xlsx'],
  'hospital': 'ascension st vincents riverside',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '100307',
  'filenames': ['260479484_ascension-st-vincents-southside_standardcharges.xlsx'],
  'hospital': 'ascension st vincents southside',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '100321',
  'filenames': ['461523194_ascension-st-vincents-clay-county_standardcharges.xlsx'],
  'hospital': 'ascension st vincents clay county',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '100313',
  'filenames': ['300577249_ascension-sacred-heart-gulf_standardcharges.xlsx'],
  'hospital': 'ascension sacred heart gulf',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '100026',
  'filenames': ['900799724_ascension-sacred-heart-bay_standardcharges.xlsx'],
  'hospital': 'ascension sacred heart bay ',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '140122',
  'filenames': ['362276984_adventist-hinsdale-hospital_standardcharges.xlsx'],
  'hospital': 'adventist hinsdale hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140304',
  'filenames': ['651219504_adventist-bolingbrook-hospital_standardcharges.xlsx'],
  'hospital': 'adventist bolingbrook hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140258',
  'filenames': ['362596381_alexian-brothers-medical-center-includes-alexian-brothers-rehab-hospital_standardcharges.xlsx'],
  'hospital': 'alexian brothers medical center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140290',
  'filenames': ['364251846_st-alexius-medical-center-incl-womens-and-childrens-hospitals_standardcharges.xlsx'],
  'hospital': 'st alexius medical center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140224',
  'filenames': ['362235165_presence-st-joseph-hospital-chicago_standardcharges.xlsx'],
  'hospital': 'presence st joseph hospital  chicago',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140180',
  'filenames': ['362235165_presence-st-mary-and-elizabeth-medical-center_standardcharges.xlsx'],
  'hospital': 'presence st mary and elizabeth medical center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140217',
  'filenames': ['364195126_presence-st-joseph-hospital-elgin_standardcharges.xlsx'],
  'hospital': 'presence st joseph hospital  elgin',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '150010',
  'filenames': ['350992717_ascension-st-vincent-kokomo-_standardcharges.xlsx'],
  'hospital': 'ascension st vincent kokomo',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '150084',
  'filenames': ['350869066_ascension-st-vincent-hospital_standardcharges.xlsx'],
  'hospital': 'ascension st vincent hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '150088',
  'filenames': ['460877261_ascension-st-vincent-anderson_standardcharges.xlsx'],
  'hospital': 'ascension st vincent anderson',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '150100',
  'filenames': ['350869065_ascension-st-vincent-evansville_standardcharges.xlsx'],
  'hospital': 'ascension st vincent evansville',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '150157',
  'filenames': ['743107055_ascension-st-vincent-carmel_standardcharges.xlsx'],
  'hospital': 'ascension st vincent carmel',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '150181',
  'filenames': ['454243702_ascension-st-vincent-fishers_standardcharges.xlsx'],
  'hospital': 'ascension st vincent fishers',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151301',
  'filenames': ['352103153_ascension-st-vincent-randolph_standardcharges.xlsx'],
  'hospital': 'ascension st vincent randolph',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151303',
  'filenames': ['351841606_ascension-st-vincent-jennings_standardcharges.xlsx'],
  'hospital': 'ascension st vincent jennings',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151307',
  'filenames': ['350784551_ascension-st-vincent-williamsport_standardcharges.xlsx'],
  'hospital': 'ascension st vincent williamsport',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151308',
  'filenames': ['350876389_ascension-st-vincent-mercy_standardcharges.xlsx'],
  'hospital': 'ascension st vincent mercy',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151309',
  'filenames': ['352112529_ascension-st-vincent-clay_standardcharges.xlsx'],
  'hospital': 'ascension st vincent clay',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151314',
  'filenames': ['270847538_ascension-st-vincent-salem_standardcharges.xlsx'],
  'hospital': 'ascension st vincent salem',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151325',
  'filenames': ['351343019_ascension-st-vincent-warrick_standardcharges.xlsx'],
  'hospital': 'ascension st vincent warrick',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '151335',
  'filenames': ['272192831_ascension-st-vincent-dunn_standardcharges.xlsx'],
  'hospital': 'ascension st vincent dunn',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '171337',
  'filenames': ['721526400_wamego-health-center_standardcharges.xlsx'],
  'hospital': 'wamego health center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '210011',
  'filenames': ['520591657_saint-agnes-hospital_standardcharges.xlsx'],
  'hospital': 'saint agnes hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/md/'},
{'facId': '380052',
  'filenames': ['oregon-idaho-shoppable.xlsx',
                'oregon-idaho-standard-charge.xlsx'],
  'hospital': 'saint alphonsus',
  'url': 'https://www.trinity-health.org/assets/documents/price-transparency/'},
 {'facId': '130006',
  'filenames': ['6e1081bcb1874e2d95a11d69602d3f9f.csv'],
  'hospital': 'st lukes boise',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '131311',
  'filenames': ['bfe552eaa95e44468cf5eba73162d0eb.csv'],
  'hospital': 'st lukes elmore',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '130002',
  'filenames': ['157e1df7542a49a89f50c6a994842548.csv'],
  'hospital': 'st lukes magic valley',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '',
  'filenames': ['6e1081bcb1874e2d95a11d69602d3f9f.csv'],
  'hospital': 'st lukes meridian',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '130071',
  'filenames': ['9ab33606b1e842f1b4a76e8f1ef3a1dc.csv'],
  'hospital': 'st lukes nampa',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '131323',
  'filenames': ['db6204a47ea74226b7ff97bf448936a8.csv'],
  'hospital': 'st lukes wood river',
  'url': 'https://www.stlukesonline.org/resources/before-your-visit/~/media/'},
 {'facId': '100131',
  'filenames': ['752379007_aventura-hospital-medical-center_standardcharges.csv'],
  'hospital': 'aventura hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '490112',
  'filenames': ['54-1779911_cjw-medical-center_standardcharges.csv'],
  'hospital': 'chippenham hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110164',
  'filenames': ['62-1736983_coliseum-medical-centers_standardcharges.csv'],
  'hospital': 'coliseum health system',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450788',
  'filenames': ['752387418_corpus-christi-medical-center_standardcharges.csv'],
  'hospital': 'corpus christi medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110177',
  'filenames': ['58-1162801_doctors-hospital-of-augusta_standardcharges.csv'],
  'hospital': 'doctors hospital of augusta',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '420085',
  'filenames': ['621768105_grand-strand-medical-center_standardcharges.csv'],
  'hospital': 'grand strand medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450222',
  'filenames': ['82-1635538_hca-houston-med-ctr_standardcharges.csv'],
  'hospital': 'hca houston healthcare medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450638',
  'filenames': ['62-1619857_hca-houston-n-cypress_standardcharges.csv'],
  'hospital': 'hca houston healthcare cypress fairbanks',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1619857_hca-houston-kingwood_standardcharges.csv'],
  'hospital': 'hca houston healthcare kingwood',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['621801360_hca-houston-mainland_standardcharges.csv'],
  'hospital': 'hca houston healthcare mainland',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1619857_hca-houston-n-cypress_standardcharges.csv'],
  'hospital': 'hca houston healthcare north cypress, a campus of hca houston '
              'healthcare kingwood',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['GulfCoastDivision_HCAHoustonSpecHospMc_CM.csv'],
  'hospital': 'hca houston healthcare – medical center specialty',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['84-1321373_centennial-healthcare-plaza_standardcharges.csv'],
  'hospital': 'centennial hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['84-1321373_the-medical-center-aurora_standardcharges.csv'],
  'hospital': 'the medical center of aurora',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['84-1321373_the-medical-center-aurora_standardcharges.csv'],
  'hospital': 'the medical center of aurora',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['84-1321373_southwest-er_standardcharges.csv'],
  'hospital': 'swedish southwest er',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1694180_jfk-medical-center-north-campus_standardcharges.csv'],
  'hospital': 'jfk medical center north campus',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['54-1779911_cjw-medical-center_standardcharges.csv'],
  'hospital': 'johnstonwillis hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['621596506_lakeview-regional-medical-center_standardcharges.csv'],
  'hospital': 'lakeview regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100248',
  'filenames': ['62-1026428_largo-medical-center-indian-rocks_standardcharges.csv'],
  'hospital': 'largo medical center indian rocks',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '100246',
  'filenames': ['591764486_lawnwood-regional-medical-center_standardcharges.csv'],
  'hospital': 'lawnwood medical center  heart institute',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450647',
  'filenames': ['62-1682198_medical-city-dallas_standardcharges.csv'],
  'hospital': 'medical city dallas',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['621682203_medical-city-frisco_standardcharges.csv'],
  'hospital': 'medical city frisco',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '454094',
  'filenames': ['62-1797829_medical-city-green-oaks-hospital-dallas_standardcharges.csv'],
  'hospital': 'medical city green oaks hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450403',
  'filenames': ['62-1682207_medical-city-mckinney_standardcharges.csv'],
  'hospital': 'medical city mckinney',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1682198_medical-city-heart-spine_standardcharges.csv'],
  'hospital': 'medical city spine hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110036',
  'filenames': ['821969974_memorial-health-umc-savannah_standardcharges.csv'],
  'hospital': 'memorial health',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '110003',
  'filenames': ['81-4223395_memorial-satilla-health_standardcharges.csv'],
  'hospital': 'memorial satilla health',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1372389_mercy-hospital_standardcharges.csv'],
  'hospital': 'mercy miami hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '340002',
  'filenames': ['832048706_mission-hospital_standardcharges.csv'],
  'hospital': 'mission health',
  'url': 'https://missionhealth.org/kaGZs2YoXr/'},
 {'facId': '100212',
  'filenames': ['59-1479652_ocala-regional-medical-center_standardcharges.csv'],
  'hospital': 'ocala health',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '170176',
  'filenames': ['45-0503116_overland-park-regional-medical-center_standardcharges.csv'],
  'hospital': 'overland park regional medical center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['62-1113733_henrico-doctors-hospital_standardcharges.csv'],
  'hospital': 'parham doctors hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '260027',
  'filenames': ['54-2092552_research-medical-center_standardcharges.csv'],
  'hospital': 'research psychiatric center',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['621113733_retreat-hospital_standardcharges.csv'],
  'hospital': 'retreat doctors hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450809',
  'filenames': ['74-2781812_st-davids-medical-center_standardcharges.csv'],
  'hospital': 'st davids healthcare',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '420079',
  'filenames': ['621768106_trident-regional-medical-center_standardcharges.csv'],
  'hospital': 'trident health system',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440161',
  'filenames': ['62-1113737_centennial-medical-center_standardcharges.csv'],
  'hospital': 'tristar centennial parthenon pavilion',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '',
  'filenames': ['61-0724492_greenview-regional-hospital_standardcharges.csv'],
  'hospital': 'tristar greenview',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '180124',
  'filenames': ['62-1560757_skyline-madison-campus_standardcharges.csv'],
  'hospital': 'tristar skyline madison campus',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440197',
  'filenames': ['62-1113737_southern-hills-medical-center_standardcharges.csv'],
  'hospital': 'tristar southern hills',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440227',
  'filenames': ['62-1113737_stonecrest-medical-center_standardcharges.csv'],
  'hospital': 'tristar stonecrest',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '440150',
  'filenames': ['621113737_summit-medical-center_standardcharges.csv'],
  'hospital': 'tristar summit',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50481',
  'filenames': ['95-2624909_west-hills-hospital-medical-center_standardcharges.csv'],
  'hospital': 'west hills hospital',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '450674',
  'filenames': ['621810381_womans-hospital-of-texas_standardcharges.csv'],
  'hospital': 'womans hospital of texas',
  'url': 'https://core.secure.ehc.com/src/util/detail-price-list/'},
 {'facId': '50760',
  'filenames': ['941340523_AntiochMedicalCenter_standardcharges.xlsx',
                '941340523_AntiochMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'antioch medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '50512',
  'filenames': ['941340523_FremontMedicalCenter_standardcharges.xlsx',
                '941340523_FremontMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'fremont medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '50710',
  'filenames': ['941340523_FresnoMedicalCenter_standardcharges.xlsx',
                '941340523_FresnoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'fresno medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '50075',
  'filenames': ['941340523_OaklandMedicalCenter_standardcharges.xlsx',
                '941340523_OaklandMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'oakland medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '50541',
  'filenames': ['941340523_RedwoodCityMedicalCenter_standardcharges.xlsx',
                '941340523_RedwoodCityMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'redwood city medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '',
  'filenames': ['941340523_RichmondMedicalCenter_standardcharges.xlsx',
                '941340523_RichmondMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'richmond medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050674',
  'filenames': ['941340523_SacramentoMedicalCenter_standardcharges.xlsx',
                '941340523_SacramentoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'sacramento medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050076',
  'filenames': ['941340523_SanFranciscoMedicalCenter_standardcharges.xlsx',
                '941340523_SanFranciscoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san francisco medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050604',
  'filenames': ['941340523_SanJoseMedicalCenter_standardcharges.xlsx',
                '941340523_SanJoseMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san jose medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050777',
  'filenames': ['941340523_SanLeandroMedicalCenter_standardcharges.xlsx',
                '941340523_SanLeandroMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san leandro medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050510',
  'filenames': ['941340523_SanRafaelMedicalCenter_standardcharges.xlsx',
                '941340523_SanRafaelMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san rafael medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050071',
  'filenames': ['941340523_SantaClaraMedicalCenter_standardcharges.xlsx',
                '941340523_SantaClaraMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'santa clara medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050674',
  'filenames': ['941340523_SouthSacramentoMedicalCenter_standardcharges.xlsx',
                '941340523_SouthSacramentoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'south sacramento medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050070',
  'filenames': ['941340523_SouthSanFranciscoMedicalCenter_standardcharges.xlsx',
                '941340523_SouthSanFranciscoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'south san francisco medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050084',
  'filenames': ['941340523_StocktonMedicalCenter_standardcharges.xlsx',
                '941340523_StocktonMedicalCenter_shoppableservices.xlsx'],
  'hospital': "St. Joseph's Medical Center",
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050767',
  'filenames': ['941340523_VacavilleMedicalCenter_standardcharges.xlsx',
                '941340523_VacavilleMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'vacaville medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050073',
  'filenames': ['941340523_VallejoMedicalCenter_standardcharges.xlsx',
                '941340523_VallejoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'vallejo medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050072',
  'filenames': ['941340523_WalnutCreekMedicalCenter_standardcharges.xlsx',
                '941340523_WalnutCreekMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'walnut creek medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050609',
  'filenames': ['941340523_AnaheimMedicalCenter_standardcharges.xlsx',
                '941340523_AnaheimMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'orange county – anaheim medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050609',
  'filenames': ['941340523_IrvineMedicalCenter_standardcharges.xlsx',
                '941340523_IrvineMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'orange county – irvine medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050723',
  'filenames': ['941340523_BaldwinParkMedicalCenter_standardcharges.xlsx',
                '941340523_BaldwinParkMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'baldwin park medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050139',
  'filenames': ['941340523_DowneyMedicalCenter_standardcharges.xlsx',
                '941340523_DowneyMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'downey medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050140',
  'filenames': ['941340523_FontanaMedicalCenter_standardcharges.xlsx',
                '941340523_FontanaMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san bernardino – fontana medical center area',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050140',
  'filenames': ['941340523_OntarioMedicalCenter_standardcharges.xlsx',
                '941340523_OntarioMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san bernardino – ontario medical center area',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050138',
  'filenames': ['941340523_LosAngelesMedicalCenter_standardcharges.xlsx',
                '941340523_LosAngelesMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'los angeles sunset medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050137',
  'filenames': ['941340523_PanoramaMedicalCenter_standardcharges.xlsx',
                '941340523_PanoramaMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'panorama medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050765',
  'filenames': ['941340523_MorenoValleyMedicalCenter_standardcharges.xlsx',
                '941340523_MorenoValleyMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'moreno valley medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050515',
  'filenames': ['941340523_SanDiegoMedicalCenter_standardcharges.xlsx',
                '941340523_SanDiegoMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'san diego zion medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050411',
  'filenames': ['941340523_SouthBayMedicalCenter_standardcharges.xlsx',
                '941340523_SouthBayMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'south bay medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050561',
  'filenames': ['941340523_WestLosAngelesMedicalCenter_standardcharges.xlsx',
                '941340523_WestLosAngelesMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'west los angeles medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '050677',
  'filenames': ['941340523_WoodlandHillsMedicalCenter_standardcharges.xlsx',
                '941340523_WoodlandHillsMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'woodland hills medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '120011',
  'filenames': ['941105628_MoanaluaMedicalCenter_standardcharges.xlsx',
                '941105628_MoanaluaMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'moanalua medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '380091',
  'filenames': ['941105628_SunnysideMedicalCenter_standardcharges.xlsx',
                '941105628_SunnysideMedicalCenter_shoppableservices.xlsx'],
  'hospital': 'sunnyside medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '500052',
  'filenames': ['910511770_CentralHospital_standardcharges.xlsx',
                '910511770_CentralHospital_shoppableservices.xlsx'],
  'hospital': 'central medical center',
  'url': 'https://healthy.kaiserpermanente.org/content/dam/kporg/final/documents/health-plan-documents/coverage-information/'},
 {'facId': '010011',
  'filenames': ['630578923_ascension-saint-vincents-east_standardcharges.xlsx'],
  'hospital': 'saint vincents east',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '011305',
  'filenames': ['630909073_saint-vincents-blount_standardcharges.xlsx'],
  'hospital': 'saint vincents blount',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '010056',
  'filenames': ['630288864_saint-vincents-birmingham_standardcharges.xlsx'],
  'hospital': 'saint vincents birmingham',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '010173',
  'filenames': ['810935368_saint-vincents-chilton_standardcharges.xlsx'],
  'hospital': 'saint vincents chilton',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '010130',
  'filenames': ['631146531_saint-vincents-saint-clair_standardcharges.xlsx'],
  'hospital': 'saint vincents saint clair',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '010090',
  'filenames': ['630288861_ascension-providence_standardcharges.xlsx'],
  'hospital': 'ascension providence',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/al/'},
 {'facId': '100025',
  'filenames': ['590634434_ascension-sacred-heart-pensacola_standardcharges.xlsx'],
  'hospital': 'ascension sacred heart pensacola',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '100292',
  'filenames': ['721529708_ascension-sacred-heart-emerald-coast_standardcharges.xlsx'],
  'hospital': 'ascension sacred heart emerald coast',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/fl/'},
 {'facId': '140065',
  'filenames': ['364257550_adventist-lagrange-hospital_standardcharges.xlsx'],
  'hospital': 'adventist lagrange hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140292',
  'filenames': ['363208390_adventist-glenoaks-hospital_standardcharges.xlsx'],
  'hospital': 'adventist glenoaks hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '144031',
  'filenames': ['364251848_alexian-brothers-behavioral-health-hospital_standardcharges.xlsx'],
  'hospital': 'alexian brothers behavioral health hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '142011',
  'filenames': ['362235165_presence-holy-family-medical-center_standardcharges.xlsx'],
  'hospital': 'AMITA Health Holy Family Medical Center Des Plaines',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140117',
  'filenames': ['362235165_presence-resurrection-medical-center_standardcharges.xlsx'],
  'hospital': 'presence resurrection medical center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140174',
  'filenames': ['364195126_presence-mercy-medical-center-aurora_standardcharges.xlsx'],
  'hospital': 'presence mercy medical center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140080',
  'filenames': ['362235165_presence-st-francis-hospital-evanston_standardcharges.xlsx'],
  'hospital': 'presence st francis hospital  evanston',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140007',
  'filenames': ['364195126_presence-st-joseph-medical-center-joliet_standardcharges.xlsx'],
  'hospital': 'presence st joseph medical center  joliet',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '140155',
  'filenames': ['364195126_presence-st-marys-hospital-kankakee_standardcharges.xlsx'],
  'hospital': 'presence st marys hospital  kankakee',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/il/'},
 {'facId': '150153',
  'filenames': ['364492612_ascension-st-vincent-heart-center_standardcharges.xlsx'],
  'hospital': 'ascension st vincent heart center',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '152020',
  'filenames': ['351712001_ascension-st-vincent-seton-specialty-hospital_standardcharges.xlsx'],
  'hospital': 'ascension st vincent seton specialty hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/in/'},
 {'facId': '170142',
  'filenames': ['481186704_ascension-via-christi-hospital-_standardcharges.xlsx'],
  'hospital': 'ascension via christi hospital manhattan',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '170006',
  'filenames': ['480543778_ascension-via-christi-hospital_standardcharges.xlsx'],
  'hospital': 'ascension via christi hospital pittsburg',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '170122',
  'filenames': ['481172106_ascension-via-christi-st-francis-_standardcharges.xlsx'],
  'hospital': 'ascension via christi st francis',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '170200',
  'filenames': ['271965272_ascension-via-christi-st-teresa_standardcharges.xlsx'],
  'hospital': 'ascension via christi st teresa',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '173028',
  'filenames': ['481158274_ascension-via-christi-rehabiliatation-hospital_standardcharges.xlsx'],
  'hospital': 'ascension via christi rehabilitation hospital',
  'url': 'https://healthcare.ascension.org/-/media/project/ascension/healthcare/price-transparency-files/ks/'},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''},
 {'facId': '', 'filenames': [], 'hospital': '', 'url': ''}
]
